//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArakiAwaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberregistration
    {
        public int id { get; set; }
        public string membername { get; set; }
        public string memberemail { get; set; }
        public string memberphone { get; set; }
        public string membergender { get; set; }
        public string memberage { get; set; }
        public string memberstate { get; set; }
        public string membercity { get; set; }
        public string memberfathername { get; set; }
        public string memberwardno { get; set; }
        public string memberlocality { get; set; }
        public string membervillage { get; set; }
        public string memberpanchayat { get; set; }
        public string memberblock { get; set; }
        public string memberwhatsupno { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
